import random

def get_random_sentence():
    sentences = [
        "Harakat natija keltiradi.",
        "Ilm eng katta boylikdir.",
        "Vaqtni qadrlash kerak.",
        "Sabr oxirida g‘alaba bor.",
        "Yaxshilik unutilmaydi.",
        "Har kuni yangi narsa o‘rgan.",
        "Xato qilish – o‘sishdir.",
        "Muhabbat qalblarni bog‘laydi.",
        "Xayrli ish qilish zavqli.",
        "Hurmat – insonning bezagi.",
        "Mehnat hamma narsani yengadi.",
        "Do‘stlik – bebaho ne’mat.",
        "Shijoat muvaffaqiyatga yetaklaydi.",
        "Haqiqat har doim ustun.",
        "Oddiylik chiroy bag‘ishlaydi.",
        "Sadoqat – chin do‘stlik asosi.",
        "Orzular harakat talab qiladi.",
        "Insof eng katta fazilat.",
        "Xushmuomala bo‘lish muhim.",
        "Baxt – ichki xotirjamlik.",
        "Adolat hammani birlashtiradi.",
        "Vijdon – eng yaxshi ustoz.",
        "Mehr qalblarni yumshatadi.",
        "O‘z ustingda ishlash foydali.",
        "Do‘st do‘stga suyanch bo‘ladi.",
        "Kamtarlik buyuklik belgisidir.",
        "Hushyorlik zararni oldini oladi.",
        "Ishonch do‘stlikning kalitidir.",
        "Ko‘ngil tozaligi go‘zallikdir.",
        "Shukronalik tinchlik olib keladi.",
        "Saxovat baraka keltiradi.",
        "Boshqalarga yordam berish savob.",
        "Hurmat va sadoqat muhim.",
        "Mehnatsevar bo‘lish yuksaltiradi.",
        "Fikr erkinligi taraqqiyotdir.",
        "Qadrdon insonlarni qadrlash kerak.",
        "Kitob eng yaxshi do‘st.",
        "O‘rganish hech qachon kech emas.",
        "Chin do‘st doimo yoningda.",
        "Katta orzular katta harakat talab qiladi.",
        "Xizmat qilish ulug‘likdir.",
        "G‘ayrat – muvaffaqiyatning siri.",
        "Hurmat – madaniyat ko‘rsatkichi.",
        "Tajriba eng yaxshi ustoz.",
        "Samimiyat yuraklarni birlashtiradi.",
        "Fidoiylik – buyuk fazilat.",
        "Murosa – tinchlik yo‘lidir.",
        "To‘g‘rilik – insoniy fazilat.",
        "O‘rganish taraqqiyotning kaliti.",
        "Haqiqat hech qachon yo‘qolmaydi.",
        "Haqiqatni gapirish jasorat talab qiladi.",
        "Mehr bilan yondashilgan har bir ish barakali bo‘ladi.",
        "Harakat qilgan odam hech qachon yutqazmaydi.",
        "Inson o‘z ustida ishlashdan to‘xtamasligi kerak.",
        "Kichik qadamlar katta natijalarga olib keladi.",
        "Baxt – oddiy narsalarda.",
        "O‘z maqsadingga intil, hech qachon taslim bo‘lma.",
        "Hayot – bu imkoniyatlar maydoni.",
        "Iloji boricha ko‘proq bilim olishga harakat qil.",
        "Muvaffaqiyat sabr bilan keladi.",
        "Yaxshilik qil va unuting, yomonlikni kechir va esdan chiqaring.",
        "Hurmat – bu ishonch kaliti.",
        "Inson o‘zini tarbiyalash bilan katta natijalarga erishadi.",
        "O‘zingni ortiqcha qiynama, tinch bo‘lish ham muhim.",
        "Odamlarga iloji boricha yordam ber.",
        "Doim to‘g‘ri yo‘ldan yur.",
        "Yaxshi niyat qil, yaxshi natija kut.",
        "Odamlar bilan yaxshi munosabat o‘rnatish – san’at.",
        "O‘z hayotingni o‘zing boshqar.",
        "Taslim bo‘lish – eng katta xato.",
        "Kitob – bilim manbai.",
        "Do‘st tanlashda hushyor bo‘l.",
        "Har kuni o‘z ustingda ishlashni davom ettir.",
        "Ko‘ngling pok bo‘lsa, hayoting chiroyli bo‘ladi.",
        "Yaxshi ishlar qilishni odat qil.",
        "Xayrli niyatlar doimo barakali bo‘ladi.",
        "O‘zgarishlardan qo‘rqma, ular yangi imkoniyatlar yaratadi.",
        "Inson sabr bilan kuchli bo‘ladi.",
        "Halollik – eng katta boylik.",
        "Vaqtingni bekorga sarflama.",
        "O‘zingni kechira bil.",
        "Shijoatli bo‘lish muvaffaqiyat kalitidir.",
        "Ilojsiz narsaning o‘zi yo‘q, faqat harakat yetishmaydi.",
        "Odamlarga samimiy bo‘lishni unutmang.",
        "Muvaffaqiyatga eltuvchi yo‘l – mehnat va sabr.",
        "Hayotda katta marralar qo‘y va ularga intil.",
        "Har bir insonning ichida katta imkoniyatlar bor.",
        "O‘zgarishga tayyor bo‘lish – taraqqiyot kaliti.",
        "Kamtarlik – insonning eng yaxshi fazilati.",
        "Harakat qilmagan kishi natija kutmasin.",
        "O‘zingga bo‘lgan ishonchni yo‘qotma.",
        "Har qanday muammo – bu yangi imkoniyat.",
        "Orzularingga ishon va ular sari intil.",
        "Boshqalarning yutug‘idan quvonish – buyuklik belgisi.",
        "Har bir inson o‘z taqdirini o‘zi yaratadi.",
        "Doim o‘z hayotini yaxshilashga harakat qil.",
        "Qiyinchiliklar seni yanada kuchliroq qiladi.",
        "To‘g‘ri yo‘ldan yurma, uni o‘zing yarat.",
        "Yaxshi odatlarni shakllantir, yomonlaridan voz kech.",
        "O‘zing uchun yashashni ham unutma.",
        "Mehnat qilsang, natija albatta bo‘ladi.",
        "Pul ketadi, bilim qoladi.",
        "Orzu qilishdan qo‘rqma, ularni ro‘yobga chiqar.",
        "Vaqtni to‘g‘ri boshqarish katta yutuqlarga olib keladi.",
        "Harakat – muvaffaqiyat kaliti.",
        "O‘zingni sev va qadrlashni unutma.",
        "O‘z qadringni bil, boshqalar ham seni hurmat qiladi.",
        "O‘z so‘zlaringga ehtiyot bo‘l, ular ta’sir kuchiga ega.",
        "Yuraging aytgan yo‘ldan yur.",
        "To‘g‘ri so‘zlash – buyuk fazilat.",
        "Qanday bo‘lishni xohlasang, shunday yashashga harakat qil.",
        "Ishga bo‘lgan mehr natija olib keladi.",
        "Vaqtingni behuda ketkazma, u qadrli.",
        "Insoniylik hech qachon eskirmaydi.",
        "Mehr-muruvvat hamma narsadan ustun.",
        "Katta maqsadlarga intil va ularni zabt et.",
        "Dushmaning ham senga dars berishi mumkin.",
        "Kichik yutuqlaringdan quvonishni o‘rgan.",
        "O‘z ustida ishlash – bu eng foydali sarmoya.",
        "Harakat qilsang, natija topasan.",
        "Ko‘proq o‘rgan, kamroq shikoyat qil.",
        "Iloji boricha ko‘proq ezgulik qil.",
        "Hamma narsa insonning qo‘lida.",
        "Muvaffaqiyat – doimiy izlanish natijasi.",
        "Boshqalarni tushunishga harakat qil.",
        "Eng yaxshi sarmoya – bu bilim.",
        "Mehnat qilish – insoniy burch.",
        "Vaqt o‘tib ketadi, lekin harakat natija qoldiradi.",
        "Qiyinchiliklarga taslim bo‘lish yaramaydi.",
        "Sabr qilsang, albatta o‘z samarasini beradi.",
        "Atrofingdagi odamlarga ilhom beruvchi bo‘l.",
        "Har bir kuningni mazmunli o‘tkaz.",
        "Tashabbuskor bo‘lish yangi yo‘llarni ochadi.",
        "Har bir imkoniyatdan foydalan.",
        "Ishga mas’uliyat bilan yondash.",
        "Har bir qilingan ezgulik qaytadi.",
        "Ko‘ngil dardini bo‘lishish ham mehr-muhabbat belgisi.",
        "Har bir kuningdan saboq ol.",
        "Ishonchli inson bo‘lish – eng katta omad.",
        "Hayotda sabrli bo‘lish muhim.",
        "Yangi imkoniyatlarni qo‘ldan boy bermang.",
        "Hamma narsaga tayyor bo‘lish muhim.",
        "Yo‘lingni o‘zing yarat, boshqalar bilan emas.",
        "Do‘stlaringga sadoqatli bo‘l.",
        "Yaxshi ish qilishdan charchama.",
        "O‘zingga qarshi ishlama, hayotingni o‘zing yarat.",
        "Senga ishonadigan odamlarning umidini puchga chiqarmaslikka harakat qil.",
        "Vaqtingni asrab-avayla.",
        "Maqsad sari yurishda to‘xtama.",
        "O‘z yo‘lingni top va undan yur.",
        "Bugun qilgan ishing ertangi kelajagingni belgilaydi.",
        "Har bir tong – yangi imkoniyat.",
        "Yangi narsalar o‘rganishdan hech qachon to‘xtama.",
        "Niyat pok bo‘lsa, yo‘llar o‘z-o‘zidan ochiladi.",
        "Boshqalar bilan emas, o‘zing bilan raqobat qil.",
        "Haqiqiy boylik – bu bilim va tajriba.",
        "Har qanday qiyinchilik – bu imkoniyat.",
        "O‘zingni isbotlash uchun ko‘p gapirish shart emas, harakat kifoya.",
        "Baxtli bo‘lish uchun avval o‘zing baxt tarqata bil.",
        "Vaziyatni emas, o‘z fikrlaringni boshqar.",
        "Bugungi harakatlaring ertangi hayotingni shakllantiradi.",
        "Mukammallik doimiy takomillashuv natijasidir.",
        "Do‘stlik ham sadoqat kabi doimiy harakat talab qiladi.",
        "Har kuni yangi imkoniyatlar yarat.",
        "Dunyo seni qanday ko‘rsa emas, sen o‘zingni qanday ko‘rsang – shunday odamsan.",
        "Ishonchli bo‘lish – eng katta kapital.",
        "O‘z ishingni chin dildan sev, shunda muvaffaqiyat keladi.",
        "Har qanday qiyin holatda ham ijobiy tomonini top.",
        "Tushkunlik – bu vaqtinchalik, harakat abadiy.",
        "Xatolar – bu o‘rganish imkoniyatlari.",
        "Katta yutuqlar kichik qadamlar bilan boshlanadi.",
        "Baxt – ko‘ngil to‘qligida.",
        "Orzularni haqiqatga aylantirish sening qo‘lingda.",
        "Odamlarga yaxshilik qil, u senga qaytadi.",
        "Har qanday sharoitda ham oldinga qadam tashla.",
        "Taqdiringni o‘zing yarat.",
        "Doim yangi bilim olishga intil.",
        "Vaqt – eng qimmat boylik.",
        "Maqsad – harakatga kuch beradi.",
        "Xotirjamlik ichki quvvatni oshiradi.",
        "Sadoqat – eng qimmat fazilat.",
        "Har kuni o‘zingga savol ber: bugun men yaxshiroq bo‘ldimmi?",
        "Boshqalar yutug‘idan ilhom ol.",
        "Qo‘rquvni emas, orzularingni tingla.",
        "Yo‘lda qoqilish – oldinga siljishning bir qismi.",
        "Ishonch – eng katta kuch.",
        "Har bir kichik yutuq seni katta g‘alabalarga yaqinlashtiradi.",
        "Har qanday boshlangan ish tugallanishi lozim.",
        "Vaziyatni o‘zgartira olmasang ham, unga bo‘lgan munosabatingni o‘zgartir.",
        "O‘zingni hurmat qil, boshqalar ham seni hurmat qiladi.",
        "Kelajaging – bugungi harakatlaring mahsuli.",
        "Ko‘proq eshit, kamroq shikoyat qil.",
        "Qo‘rqmasdan harakat qil, natija o‘zini kutib turmaydi.",
        "Tajribasiz muvaffaqiyat bo‘lmaydi.",
        "Birovning muvaffaqiyatidan ilhomlan, hasad qilma.",
        "Vaqt o‘tdi deb tashvishlanma, oldinda imkoniyatlar ko‘p.",
        "Har bir kuningda o‘sishga harakat qil.",
        "Xatolar – bu ustoz.",
        "Harakatni boshlash – g‘alabaning yarmi.",
        "Orzularing sari yurishda to‘xtama.",
        "Kim bo‘lishni xohlasang, hozirdan shunday yashashni boshlagin.",
        "O‘zingni kashf qilishdan qo‘rqma.",
        "Har qanday holatda ham samimiy bo‘l.",
        "Maqsadlarni amalga oshirish uchun harakat zarur.",
        "Intizomli bo‘lish muvaffaqiyat garovi.",
        "Ilm olishdan charchama.",
        "Hayot – bu o‘zgarishlar maydoni.",
        "Shijoat – eng katta qurol.",
        "Taraqqiyot – doimiy harakat talab qiladi.",
        "To‘g‘ri odamlar bilan yur, noto‘g‘ri odamlarni hayotingdan chiqar.",
        "Kichik ishlar katta natijalarga olib keladi.",
        "Mehnat qil, natijasi albatta bo‘ladi.",
        "Hamma narsa senga bog‘liq.",
        "Sabr bilan harakat qil, natija o‘zini ko‘rsatadi.",
        "Har bir inson o‘z imkoniyatlarini yaratadi.",
        "O‘zingni ortiqcha solishtirishdan to‘xtagin.",
        "Hech qachon kech emas.",
        "Muhimi – boshlash.",
        "Taslim bo‘lishni o‘ylama.",
        "O‘z fikrlaringni boshqara olsang, hayotingni ham boshqara olasan.",
        "Bilim – eng katta kuch.",
        "Xayrli ishlarning natijasi albatta bo‘ladi.",
        "Yo‘lingni o‘zing yarat.",
        "Yutuq – bu intizom natijasi.",
        "Sabr – eng katta kuch.",
        "Muvaffaqiyat – bu jarayon.",
        "Orzularing sari doimo harakatda bo‘l.",
        "Hayot senga imkoniyatlar taqdim etadi, ularni qo‘ldan boy bermagin.",
        "Qo‘rqma, faqat oldinga qadam tashla.",
        "Kelajakka ishonch bilan boq.",
        "Bugun qilingan kichik harakat ertangi katta natijaga aylanishi mumkin.",
        "Hech kim seni to‘xtata olmaydi, faqat o‘zing.",
        "Yaxshi fikrlar yaxshi natijalarga olib keladi.",
        "Boshqalar nima derligiga ortiqcha ahamiyat berma.",
        "O‘zingni isbotlash uchun vaqt ketkazma, o‘zing uchun yashagin.",
        "Yutuq sabr va mehnat natijasidir.",
        "Imkoniyatlar oldinga intiladiganlar uchun ochiladi.",
        "Yangi narsalarni o‘rganish – hayotni yanada qiziqarli qiladi.",
        "Tasavvur qilish – muvaffaqiyatga birinchi qadam.",
        "Bugunning ishlari ertangi kunni belgilaydi.",
        "Qanchalik ko‘p o‘rgansang, shunchalik ko‘p imkoniyatga ega bo‘lasan.",
        "Ko‘proq harakat qil, kamroq shikoyat qil.",
        "Sen kim bo‘lishni istasang, hozirdan shunday harakat qil.",
        "Orzularingni haqiqatga aylantirish faqat sening qo‘lingda.",
        "Bugun qilish kerak bo‘lgan ishni ertaga qoldirma.",
        "Hayotdagi eng katta boylik – bu vaqt.",
        "Tushkunlikka tushganingda ham orzularingni esla.",
        "Orzularing qanchalik katta bo‘lsa, harakatlaring ham shunchalik kuchli bo‘lishi kerak.",
        "Har bir inson o‘z yulduzini yaratadi.",
        "Eng yaxshi qaror – boshlash.",
        "Hech qachon to‘xtama, to‘xtash – orqaga ketish demakdir.",
        "Harakat natijasiz bo‘lmaydi.",
        "Har bir kun yangi imkoniyatlarga to‘la.",
        "Hayot oldinga yuruvchilar uchun mo‘jizalar yaratadi.",
        "Bugungi harakatlaring ertangi hayotingni shakllantiradi.",
        "Muvaffaqiyat sirlaridan biri – sabr va doimiy harakat.",
        "Har qanday kichik o‘zgarish katta natijalarga olib keladi.",
        "Hayot – bu imkoniyatlarni izlash san’ati.",
        "Doimo yangilikka intil, eskilikda qolib ketma.",
        "Kelajagingni hozirdan boshlab yarat.",
        "Harakat qilmasang, natijani kutma.",
        "Orzularing yo‘lida hech qachon taslim bo‘lma.",
        "Bugun qilgan ishing ertangi natijangdir.",
        "Hech qachon o‘z imkoniyatlaringni kam baholama.",
        "Muvaffaqiyatli bo‘lish uchun har kuni o‘zingni rivojlantir.",
        "Yaxshi fikrlash yaxshi natijalarga olib keladi.",
        "Qiyinchiliklar sening kuchliroq bo‘lishingga xizmat qiladi.",
        "Oldinga yur, orqaga nazar solish faqat xotiralar uchun kerak.",
        "Harakat qilmagan inson yutuqqa erisha olmaydi.",
        "Birinchi qadam – eng muhim qadam.",
        "O‘zgarishga ochiq bo‘l, yangi yo‘llarni izla.",
        "Bugun bir qadam tashlasang, ertaga ikki qadam oldinga ketasan.",
        "Har bir insonning ichida katta imkoniyatlar yashirin.",
        "Hayotdagi eng katta boylik – vaqtni to‘g‘ri ishlatish.",
        "Imkoniyatni kutish o‘rniga o‘zing yarat.",
        "Orzularing sari yurishda hech qachon to‘xtama.",
        "Har kuni o‘z ustingda ishlash seni oldinga siljitadi.",
        "Hayot – bu senga berilgan imkoniyat, undan unumli foydalan.",
        "Yo‘lingdan adashma, maqsadingni aniq belgilab ol.",
        "Bugun yaxshi ish qil, ertaga mukofotini olasan.",
        "Katta natijalar sabr va mehnat natijasidir.",
        "Boshqalarning fikridan ko‘ra, o‘z qalbingni tingla.",
        "O‘zingni hech kim bilan solishtirma, faqat kechagi o‘zing bilan.",
        "Muvaffaqiyat – bu doimiy o‘sish va harakat.",
        "To‘g‘ri fikrlash natijani o‘zgartiradi.",
        "Har kuni yangi maqsad qo‘y va unga intil.",
        "Kelajagingga ishon, lekin hozirdan harakat qil.",
        "Har qanday muammo yangi imkoniyat eshigidir.",
        "Harakat qilsang, omad o‘zingni topadi.",
        "O‘zgarishlar har doim yangi yo‘llar ochadi.",
        "Hamma narsa sening qo‘lingda.",
        "Maqsadingni aniq belgilab ol va unga qarab yur.",
        "Boshqalarga foydali bo‘lish hayotingni mazmunli qiladi.",
        "Har kuni yangi imkoniyatlar yarat.",
        "Tashabbuskor bo‘lgan inson doim yutadi.",
        "Har qanday to‘siq – bu yangi yutuqqa yo‘l.",
        "Shaxsiy taraqqiyotga sarmoya kirit, u eng yaxshi sarmoyadir.",
        "Hayotdagi eng katta dushman – dangasalik.",
        "O‘zingni rivojlantirish uchun har kuni bir narsa o‘rgan.",
        "Qiyinchiliklar seni yanada kuchliroq qiladi.",
        "Har qanday sharoitda ham oldinga qadam tashla.",
        "O‘z yo‘lingni yarat va hech kimni ayblama.",
        "Yaxshi ish qilish odat bo‘lishi kerak.",
        "Har qanday katta muvaffaqiyat kichik qadamlardan boshlanadi.",
        "O‘zingga sodiq qol, boshqalar sen haqingda nima o‘ylashidan qo‘rqma.",
        "Ilm olish – eng yaxshi sarmoya.",
        "O‘zingga ishonmasang, hech kim senga ishonmaydi.",
        "Ko‘proq o‘rgan, kamroq shikoyat qil.",
        "Harakat qil, natija keladi.",
        "Kelajaging bugundan boshlanadi.",
        "Sabr bilan ishlash natija beradi.",
        "Orzularingni haqiqatga aylantirish faqat o‘zingga bog‘liq.",
        "Omad tayyor bo‘lganlarga keladi.",
        "Har qanday vaziyatdan saboq ol.",
        "Hech qachon ortga qarab yashama.",
        "O‘zgarishlarni o‘zing yarat.",
        "Bugungi kichik harakat ertangi katta yutuqlarga sabab bo‘ladi.",
        "Har qanday muammo – bu yangi imkoniyat.",
        "O‘z ishingni sev, shunda muvaffaqiyat keladi.",
        "Yangi narsalarni o‘rganish hayotni qiziqarli qiladi.",
        "Har qanday vaziyatda ham o‘sishga intil.",
        "Hayot senga imkoniyatlar beradi, ularni qo‘ldan boy bermagin.",
        "Qo‘rqma, faqat oldinga yur.",
        "Kelajakka ishonch bilan boq.",
        "Omad harakat qilganlarni topadi.",
        "Bugungi kichik harakat ertangi katta natijadir.",
        "Hech kim seni to‘xtata olmaydi, faqat o‘zing.",
        "Yaxshi fikrlar yaxshi natijalarga olib keladi.",
        "Orzularing sari yurishda hech qachon taslim bo‘lma.",
        "O‘zing uchun yashashni unutma.",
        "Orzularingni himoya qil, hech kim sening o‘rningga ularni amalga oshirmaydi.",
        "Muvaffaqiyatli insonlar har kuni bir qadam oldinga yuradi.",
        "Tinchlik ichki baxtning kalitidir.",
        "Katta natijalar uchun katta harakatlar talab qilinadi.",
        "Hayotda eng muhim narsa – o‘zing bo‘lish.",
        "Har qanday vaziyatdan ijobiy tomon topishga harakat qil.",
        "Yo‘lingdagi to‘siqlar seni kuchliroq qiladi.",
        "Muvaffaqiyat shunchaki omad emas, balki harakat natijasidir.",
        "Ilm – eng katta kuch.",
        "Barcha imkoniyatlarni izlab top.",
        "Xatolarni xatolik deb emas, tajriba deb qabul qil.",
        "Hech qachon o‘z orzularingdan voz kechma.",
        "Har qanday sharoitda ham oldinga qadam tashla.",
        "O‘z imkoniyatlaringni hech qachon kam baholama.",
        "Har bir inson o‘z taqdirini o‘zi yaratadi.",
        "Muvaffaqiyatli insonlar doim yangi imkoniyatlarni izlaydi.",
        "Kelajak bugundan boshlanadi.",
        "Katta natijalar kichik qadamlardan boshlanadi.",
        "Boshqalar nima deyishi muhim emas, muhim narsa – o‘zing qanday yashayotganing.",
        "Harakat qilmasang, natijani kutma.",
        "Maqsad sari yurishda hech qachon to‘xtama.",
        "Taslim bo‘lish eng katta xato.",
        "Orzularingga ishon va ular sari intil.",
        "Bugun qilgan ishing kelajagingni belgilaydi.",
        "Muvaffaqiyat sabr bilan keladi.",
        "Harakat qilgan odam hech qachon yutqazmaydi.",
        "O‘z oldingga katta maqsadlar qo‘y va ularga intil.",
        "Har bir kun – bu yangi imkoniyat.",
        "O‘zingga sodiq qol va orzularingga ergash.",
        "O‘rganish hech qachon kech emas.",
        "Maqsadlaringni aniq belgilash – muvaffaqiyat kaliti.",
        "Baxt – bu harakat qilish jarayonida bo‘lishdir.",
        "Muvaffaqiyat – bu bir kunlik natija emas, balki davomiy harakat natijasi.",
        "Hech qachon o‘z imkoniyatlaringni kam baholama.",
        "Bugungi harakatlaring ertangi kelajagingni belgilaydi.",
        "Hayot faqatgina kutish emas, harakat qilish ham muhim.",
        "Xatolar – bu o‘rganish imkoniyati.",
        "Kimdir seni to‘xtatishini kutma, o‘zing harakat qil.",
        "Har bir insonda ulkan imkoniyatlar yashirin.",
        "Harakat – bu eng yaxshi reja.",
        "Orzularingni faqat o‘zing ro‘yobga chiqarishing mumkin.",
        "Taslim bo‘lish – eng katta yo‘qotish.",
        "O‘zingning qobiliyatlaringni kashf et.",
        "Yo‘lingdagi har bir qiyinchilik seni kuchliroq qiladi.",
        "O‘zgarishga tayyor bo‘l, yangi imkoniyatlar ochiladi.",
        "Hech qachon qo‘rqma, faqat oldinga qadam tashla.",
        "Hayot – bu senga berilgan imkoniyat, undan unumli foydalan.",
        "Sabr – katta natijalarga yetaklovchi kuch.",
        "Barcha muammolar yechimga ega.",
        "Kelajagingni hozirdan boshlash muhim.",
        "Har qanday sharoitda ham oldinga intilish muhim.",
        "O‘zingni yaxshi ko‘r, hurmat qil va rivojlantir.",
        "Katta yutuqlar kichik qadamlar bilan boshlanadi.",
        "Yo‘qotishlardan qo‘rqma, ular yangi boshlanishlar eshigidir.",
        "To‘g‘ri yo‘ldan yurish – muvaffaqiyat kaliti.",
        "O‘zingga ishon va hech qachon ortga qaytma.",
        "Orzularing sari yurishda hech kimni tinglama, yurakni eshit.",
        "Har bir inson o‘z hayotining me’mori.",
        "Har kuni o‘zingni yaxshilash ustida ishlash kerak.",
        "Hech qachon natijasiz harakat bo‘lmaydi.",
        "Orzularing uchun ishlashni to‘xtatma.",
        "Muvaffaqiyatli insonlar hech qachon taslim bo‘lmaydi.",
        "Har qanday yo‘qotish yangi boshlanish eshigini ochadi.",
        "Ko‘proq o‘rgan, kamroq bahona top.",
        "Hayot – bu yangi tajribalarni sinash imkoniyati.",
        "Yaxshi odatlarni shakllantirish hayotingni o‘zgartiradi.",
        "Tushkunlikka tushma, har doim chiqish yo‘li bor.",
        "O‘zing ustida ishlash eng foydali sarmoyadir.",
        "Kelajaging senga bog‘liq, uni o‘zing yarat.",
        "Harakat qil, shunda omad keladi.",
        "Maqsading sari harakat qil, natijalar seni kutmoqda.",
        "Har qanday qiyinchilik – bu yangi yutuqqa yo‘l.",
        "O‘zingga ishon, bu muvaffaqiyat sari birinchi qadam.",
        "O‘z yo‘lingni top va unga ergash.",
        "Ilm olish hech qachon zarar qilmaydi.",
        "Har qanday vaziyatdan ijobiy tomon topishga harakat qil.",
        "Doim yangi narsalarni o‘rganishga intil.",
        "Yaxshi natijalarga yetish uchun mehnat qilish kerak.",
        "Kelajakka intilish hozirdan boshlanadi.",
        "Xatolar – bu eng yaxshi dars.",
        "O‘zgarishlardan qo‘rqma, ularga ochiq bo‘l.",
        "Katta yutuqlar sabr va mehnat natijasidir.",
        "Kamtarlik – buyuklik belgisi.",
        "Har kuni yangi narsalarni sinab ko‘r.",
        "Har qanday muammo – bu o‘sish imkoniyati.",
        "O‘ziga ishonch – bu har qanday yutuqning kaliti.",
        "O‘zingni tushunish – bu eng katta boylik.",
        "Haqiqiy yutuqlar sabr bilan keladi.",
        "Har bir insonning ichida ulkan imkoniyat bor.",
        "O‘zingni har doim yaxshiroq qilishga harakat qil.",
        "Hayot faqat natijalar haqida emas, jarayon ham muhim.",
        "Omad kelishini kutma, harakat bilan uni chaqir.",
        "Hech qachon orzularingdan voz kechma.",
        "Yaxshi niyat va harakat yaxshi natijalar olib keladi.",
        "Kelajak bugundan boshlanadi.",
        "Muvaffaqiyat – bu tinimsiz mehnat natijasi.",
        "Har qanday muammoga yechim bor.",
        "Bugungi harakatlaring ertangi natijalaringni belgilaydi.",
        "Xayolingdan o‘tkazgan har bir g‘oya haqiqatga aylanishi mumkin.",
        "Hamma narsa senga bog‘liq, faqat harakat qil.",
        "Kelajagingni bugundan qurishni boshlang.",
        "Xato qilishdan qo‘rqma, ular seni o‘stiradi.",
        "Orzularingni ro‘yobga chiqarish sening qo‘lingda.",
        "Har qanday muammo – bu yangi imkoniyat.",
        "Taslim bo‘lish eng katta yo‘qotishdir.",
        "Har kuni yangi maqsad belgilash muvaffaqiyat kalitidir.",
        "Yo‘lingdan adashma, to‘g‘ri yo‘ldan yur.",
        "Harakat qilishga qo‘rqma, natija seni ajablantiradi.",
        "Kelajagingni qanday bo‘lishini xohlashingni o‘zing hal qil.",
        "O‘zing ustida ishlash hech qachon kech emas.",
        "Har qanday muammo o‘sish imkoniyati sifatida qabul qilinishi kerak.",
        "Yaxshi niyat doimo yaxshi natijalar olib keladi.",
        "Orzularing sari harakat qil, vaqt kutmaydi.",
        "Har qanday qiyinchilik – bu o‘zgarish uchun imkoniyat.",
        "Hech qachon o‘z qadringni past baholama.",
        "Orzularingni himoya qil va ularga intil.",
        "Har qanday vaziyatda ham o‘sishga intilish kerak.",
        "O‘zingning eng yaxshi versiyang bo‘lishga intil.",
        "Har qanday to‘siq – bu yangi imkoniyatlar eshigi.",
        "Kelajagingni rejalashtirish bugundan boshlanadi.",
        "Hayotdagi eng muhim narsa – orzularing sari intilish.",
        "O‘z yo‘lingni yarat va hech kimni ayblama.",
        "Har kuni yangi narsalarni sinash foydalidir.",
        "Hech kim seni to‘xtata olmaydi, faqat o‘zing.",
        "Omad harakat qilganlarni topadi.",
        "Hayotda katta marralar qo‘y va ularga intil.",
        "Harakat qilgan odam hech qachon yutqazmaydi.",
        "Muvaffaqiyatli insonlar har kuni bir qadam oldinga yuradi.",
        "O‘zingni har doim yaxshiroq qilishga harakat qil.",
        "Bugun qilgan harakatlaring ertangi natijalaringni belgilaydi.",
        "O‘z oldingga aniq va katta maqsadlar qo‘y.",
        "Hayotda faqat oldinga yurish muhim.",
        "Barcha buyuk ishlar kichik qadamlar bilan boshlanadi.",
        "Xatolar – bu muvaffaqiyat sari olib boradigan saboqlar.",
        "O‘zingni kashf et va o‘sishga harakat qil.",
        "Harakat qil, chunki hech narsa o‘z-o‘zidan sodir bo‘lmaydi.",
        "Kechagi kun o‘tib ketdi, bugun esa yangi imkoniyat.",
        "Yaxshi odatlar shakllantirish muvaffaqiyat sari yo‘l ochadi.",
        "Qiyinchiliklar seni kuchaytiradi, sustlashtirmaydi.",
        "Yo‘qotishlardan qo‘rqma, ular yangi yutuqlarga yo‘l ochadi.",
        "Sabr bilan harakat qil, natijalar seni hayratga soladi.",
        "Kelajakni bugundan qurish muhim.",
        "Doim yangi narsalarni sinab ko‘rishdan qo‘rqma.",
        "O‘zingga bo‘lgan ishonch eng katta boylikdir.",
        "Har qanday vaziyatda ijobiy tomonlarni izlashni o‘rgan.",
        "Har bir inson o‘z hayotining me’mori.",
        "Katta yutuqlarga erishish uchun kichik g‘alabalardan boshlash kerak.",
        "Muvaffaqiyat hech qachon taslim bo‘lmaganlar bilan bo‘ladi.",
        "O‘z maqsading sari qat’iyat bilan harakat qil.",
        "O‘zingni rivojlantirish uchun har kuni bir narsa o‘rgan.",
        "Natijalar harakat natijasidir, shuning uchun to‘xtama.",
        "Hayotda hamma narsa senga bog‘liq, faqat harakat qil.",
        "Yo‘lingdan adashma, to‘g‘ri yo‘ldan yur.",
        "O‘zingni kechira bil, lekin xatolardan saboq ol.",
        "O‘zingga ishon va hech qachon orqaga qaramagin.",
        "Muvaffaqiyatga eltuvchi yo‘l – bu doimiy o‘sish.",
        "Orzularing sari dadil qadam tashlash muhim.",
        "Har kuni yaxshiroq bo‘lishga harakat qil.",
        "Qiyinchiliklar sening kuchingni sinovdan o‘tkazadi.",
        "Xato qilish – bu muvaffaqiyatga olib boradigan qadam.",
        "Harakat qil, shunda omad keladi.",
        "Har qanday to‘siq – bu yangi imkoniyat.",
        "Vaqtingni qadrlash muvaffaqiyat kalitidir.",
        "Har doim yangi marralarni zabt etishga intil.",
        "O‘z hayotingni boshqar, hech kim buni sening o‘rningga qilmaydi.",
        "O‘zing ustida ishlash – bu eng yaxshi sarmoya."
    ]
    return random.choice(sentences)
